### ISSUE TITLE
关于 data/battlefield/settings.yaml 配置文件内容的解释

### ISSUE THREAD

**Issue by Administrator-Xorex** [KomeiDiSanXian/BFHelper#20]
Hi，我在我的服务器上成功部署了 go-cqhttp 和您的 BFHelper，现在 BFHelper 可以成功的收到 QQ 的消息。
但由于我不太明白 settings.yaml 里面配置选项应该如何填写，所以 BFHelper 在我这里收到对应指令没有返回信息，请问可以辛苦您帮忙讲一下这个应该去哪里获取需要填写的信息吗（我主要是为了能查询自己的战绩，不涉及到管理服务器的功能）？

```yaml
Account:
  UserName: your_ea_account@example.com
  Password: yourpassword
  # 以下信息你可以自己填写进去
  Session: "-"
  Token: "-"
  SID: "-"
  Remid: "-"
# 这个API key 请去联系SakuraKooi 本人获取，或者等什么时候我自己写
SakuraKooi:
  SakuraID: yourid
  SakuraToken: yourtoken
  MFASecret: "" # 开启了两步验证就要填这个, 类似于2GFS PQSN 7D25 6HRG, 用于计算MFA Code
```

此外，谢谢您对 BattleField 社区的贡献！
